### ISSUE TITLE
Selectable data list bugs

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3847]
There should be no shadow between adjacent selected rows.

<img width="289" alt="Screen Shot 2021-02-09 at 6 02 55 PM" src="https://user-images.githubusercontent.com/35148959/107444945-2bdd6100-6b01-11eb-906e-684b82335a0d.png">

There is currently a thin grey border showing between adjacent selected rows when you hover over one.

<img width="334" alt="Screen Shot 2021-02-09 at 6 02 40 PM" src="https://user-images.githubusercontent.com/35148959/107444949-2ed85180-6b01-11eb-80e1-c8b721e69cb9.png">

**Comment by eliranmal** [comment]
hey, i'm looking for issues to solve :octocat: 

@mcoker can you please assign this to me?

**Comment by mcoker** [comment]
@eliranmal of course, thanks for taking it on!!

**Comment by eliranmal** [comment]
@mcoker - i'm testing against the main branch, and can't reproduce any of the three problems.

could they be fixed by now? or am i missing something?  
it would be great if you could provide any examples for these bugs (live demos / links to the faulty documentation / link to a specific build/deployment).

**Comment by mcoker** [comment]
@eliranmal my apologies for the delay! I'm still seeing it here - https://www.patternfly.org/v4/components/data-list/html#selectable-rows

I'm using chrome, and the top shadow is visible on the "secondary content" item by default
* An aside, we should probably add "(selected)" to the first item that says "primary content" since it's selected, to match the secondary content item.

<img width="907" alt="Screen Shot 2022-03-18 at 3 06 20 PM" src="https://user-images.githubusercontent.com/35148959/159076275-551a2d54-2ba8-47af-812c-fa4b018f67a3.png">

If I hover "primary content" while it's selected, this grey border along the left between the select items is visible

<img width="320" alt="Screen Shot 2022-03-18 at 3 08 10 PM" src="https://user-images.githubusercontent.com/35148959/159076376-555d18a3-3508-4f8f-a58b-53a7822a190a.png">

And in the selectable/expandable example - https://www.patternfly.org/v4/components/data-list/html#selectable-expandable-rows- I'm still seeing that both the selected/expanded and non-selected/expanded are showing the same blue accent color. selected/expanded should be the regular dark blue that we use for regular selected (non-expandable) items.

**Comment by eliranmal** [comment]
thanks for the elaboration!

i think i got confused by the *(selected)* text (as stated on your aside note), and didn't think of the first item as being selected.

i'll review it again in light of that info, and maybe if i need a more detailed specification, i'll just give a shoutout on the PF slack to have a quick chat.

**Comment by eliranmal** [comment]
ok, sorry for the big delay (i was preoccupied with my own team's workload..).

i think i have a fix for all three, but may need some help making sure i've fulfilled the specs / design guidelines:

- **expanded items wrong color** - was an easy fix; looks like it was a bug in the example.
- **selected/expanded items undesired border on hover** - was more involved: hovering alters the z-index, and so the border would appear even if transparent (as the box would pop up the top of the stacking context). this was solved collapsing the border to 0-width, and replacing it by a bottom padding.
- **adjacent selected items undesired shadow** - this is quite complex, as there's currently no way to select next-sibling-with-classname elements, and the altering stacking context on hover would hinder any attempts to replace inner box-shadows with borders without major impl' changes.
   i managed to do it in the price of removing all shadows, so now selected items do not have intrinsic shadows - only hovered ones.
   this is also the one i'm most unsure of (in terms of following designs).

_another thing to note:_ i think i created regression - if you closely inspect the list-item colored border, on the topmost left corner of the list, you'll see that it bleeds 1px upwards. probably the result of removing the (top) box-shadow. i'll commit and push these changes, so it can be shared and verified.

i created a screen recording showing the list (with some interactions) before and after the changes, so it could serve as preliminary review, and hopefully help visualize what i'm doing.




https://user-images.githubusercontent.com/1401288/166261471-2abe7c11-79f3-4f2c-a813-0259b87428c3.mov

**Comment by mcoker** [comment]
No longer needed for v6, the linked PR was also closed - https://github.com/patternfly/patternfly/pull/4823
